import type {DesignFamily} from '~/data/catalogue';

/**
 * Editorial imagery shipped with the site (public/visuals/, generated by
 * `npm run visuals:render` from the locked masters). Product images come
 * from Shopify; these are brand/editorial assets for the homepage, design
 * pages and collection banners. V2 families have no editorial imagery yet.
 */
const BASE = '/visuals/editorial';

export const HERO_VISUAL = {
  portrait: {src: `${BASE}/hero-portrait.webp`, width: 1400, height: 1750},
  wide: {src: `${BASE}/hero-wide.webp`, width: 2400, height: 1500},
  alt: 'Mumbai Made oversized tee, tote and tumbler on a brick-red set',
};

export const DROP_DETAIL_VISUAL = {
  src: `${BASE}/drop01-detail.webp`,
  width: 2000,
  height: 1250,
  alt: 'Close-up of the Mumbai Made print: MUMBAI MADE, Est. 1995, Built here. Worn everywhere.',
};

export function familySetVisual(family: DesignFamily) {
  if (family.release !== 'v1') return null;
  return {
    src: `${BASE}/${family.handle}-set.webp`,
    width: 1200,
    height: 1500,
    alt: `${family.name}: oversized tee, tote and tumbler`,
  };
}
