// Writes catalogue/policies/*.html: the same policy text the site renders,
// ready to paste into Shopify Admin → Settings → Policies. Nothing is sent
// to Shopify. Links become absolute because Shopify shows these pages on its
// own checkout domain.
//   npm run policies:export
import {mkdirSync, writeFileSync} from 'node:fs';
import {SHOPIFY_POLICIES} from '../app/data/legal.ts';
import {SITE} from '../app/data/site.ts';

const dir = 'catalogue/policies';
mkdirSync(dir, {recursive: true});
const index: string[] = [
  '# Shopify native policies (prepared, not applied)',
  '',
  'Generated by `npm run policies:export` from `app/data/legal.ts`, the same text the storefront shows. Paste each file into Shopify Admin → Settings → Policies → the field named below, after review. Re-export after any change.',
  '',
  '| Shopify field | File |',
  '| --- | --- |',
];
for (const policy of SHOPIFY_POLICIES) {
  const html = policy.html.replace(/href="\//g, `href="${SITE.url}/`);
  const file = `${policy.handle}.html`;
  writeFileSync(`${dir}/${file}`, `${html}\n`);
  index.push(`| ${policy.shopifyField} | \`${file}\` |`);
}
writeFileSync(`${dir}/README.md`, `${index.join('\n')}\n`);
// eslint-disable-next-line no-console
console.log(`${SHOPIFY_POLICIES.length} policies → ${dir}/`);
