// Landed cost and contribution per unit, from verified inputs only.
//   npm run costs:check
//
// Reads ops/landed-cost.csv (fill it from supplier quotes, courier and
// gateway rate cards) and the retail prices in app/data/catalogue/pricing.ts.
// A row with any blank input is reported as incomplete and gets NO margin
// figure: nothing is estimated or defaulted. Writes
// catalogue/landed-cost-report.md.
import {readFileSync, writeFileSync} from 'node:fs';
import {
  PRICE_OVERRIDES_INR,
  RETAIL_PRICE_INR,
} from '../app/data/catalogue/pricing.ts';
import type {ProductTypeHandle} from '../app/data/catalogue/types.ts';

const INPUT = 'ops/landed-cost.csv';
const REPORT = 'catalogue/landed-cost-report.md';

const NUMERIC = [
  'supplier_unit_cost_inr',
  'supplier_gst_pct',
  'shipping_to_customer_inr',
  'packaging_inr',
  'gateway_fee_pct',
  'gateway_fixed_inr',
  'cod_share_pct',
  'cod_fee_inr',
  'rto_rate_pct',
  'rto_cost_inr',
  'reprint_rate_pct',
  'output_gst_pct',
] as const;
const BOOLEAN = ['supplier_cost_includes_gst', 'itc_claimable'] as const;
const TEXT = ['source', 'quote_date'] as const;

type Row = Record<string, string>;

function parseCsv(text: string): Row[] {
  const [header, ...lines] = text.trim().split(/\r?\n/);
  const keys = header.split(',');
  return lines
    .filter((line) => line.trim())
    .map((line) => {
      const cells = line.split(',');
      return Object.fromEntries(
        keys.map((k, i) => [k, (cells[i] ?? '').trim()]),
      );
    });
}

const yes = (v: string) => /^(y|yes|true|1)$/i.test(v);
const isBool = (v: string) => /^(y|yes|true|1|n|no|false|0)$/i.test(v);
const inr = (n: number) =>
  `₹${n.toLocaleString('en-IN', {maximumFractionDigits: 0})}`;
const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

const rows = parseCsv(readFileSync(INPUT, 'utf8'));
const out: string[] = [
  '# Landed cost and contribution (per unit)',
  '',
  `Generated by \`npm run costs:check\` from \`${INPUT}\` and \`app/data/catalogue/pricing.ts\`.`,
  'Rows with any blank or invalid input show no margin. Nothing is estimated.',
  '',
];
const complete: string[] = [];
const incomplete: string[] = [];

for (const row of rows) {
  const type = row.product_type as ProductTypeHandle;
  const retail = RETAIL_PRICE_INR[type];
  const label = `${type} / ${row.variant}`;
  const missing: string[] = [
    ...NUMERIC.filter((k) => row[k] === '' || Number.isNaN(Number(row[k]))),
    ...BOOLEAN.filter((k) => !isBool(row[k] ?? '')),
    ...TEXT.filter((k) => !row[k]),
  ];
  if (retail == null) missing.unshift('product_type (unknown)');
  if (missing.length) {
    incomplete.push(`| ${label} | ${missing.join(', ')} |`);
    continue;
  }

  const n = Object.fromEntries(
    NUMERIC.map((k) => [k, Number(row[k])]),
  ) as Record<(typeof NUMERIC)[number], number>;
  const gst = n.supplier_gst_pct / 100;
  const supplierNet = yes(row.supplier_cost_includes_gst)
    ? n.supplier_unit_cost_inr / (1 + gst)
    : n.supplier_unit_cost_inr;
  const supplier = yes(row.itc_claimable)
    ? supplierNet
    : supplierNet * (1 + gst);
  const netRevenue = retail / (1 + n.output_gst_pct / 100);
  const cod = n.cod_share_pct / 100;
  const payment =
    (1 - cod) * (retail * (n.gateway_fee_pct / 100) + n.gateway_fixed_inr) +
    cod * n.cod_fee_inr;
  const rto = (n.rto_rate_pct / 100) * n.rto_cost_inr;
  const reprint =
    (n.reprint_rate_pct / 100) *
    (supplier + n.shipping_to_customer_inr + n.packaging_inr);
  const landed =
    supplier +
    n.shipping_to_customer_inr +
    n.packaging_inr +
    payment +
    rto +
    reprint;
  const contribution = netRevenue - landed;

  complete.push(
    `| ${label} | ${inr(retail)} | ${inr(netRevenue)} | ${inr(supplier)} | ${inr(
      n.shipping_to_customer_inr + n.packaging_inr,
    )} | ${inr(payment)} | ${inr(rto + reprint)} | ${inr(landed)} | ${inr(
      contribution,
    )} | ${pct(contribution / netRevenue)} | ${row.source} (${row.quote_date}) |`,
  );
}

if (complete.length) {
  out.push(
    '## Complete rows',
    '',
    '| Product / variant | Retail (incl. GST) | Net revenue (ex GST) | Supplier | Ship + pack | Payment | RTO + reprint | Landed | Contribution | Margin | Source |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...complete,
    '',
    'Contribution is before marketing, overheads and income tax.',
    '',
  );
}
if (incomplete.length) {
  out.push(
    '## Incomplete rows (no margin shown)',
    '',
    '| Product / variant | Missing inputs |',
    '| --- | --- |',
    ...incomplete,
    '',
  );
}
if (Object.keys(PRICE_OVERRIDES_INR).length) {
  out.push(
    `Per-design price overrides exist (${Object.keys(PRICE_OVERRIDES_INR).join(', ')}); check them separately.`,
    '',
  );
}
out.push(
  '## Formula',
  '',
  '- Net revenue = retail ÷ (1 + output GST).',
  '- Supplier = unit cost, ex GST if input tax credit is claimable, else incl. GST.',
  '- Payment = prepaid share × (retail × gateway % + fixed fee) + COD share × COD fee. Enter gateway % including GST on the fee.',
  '- RTO = RTO rate × cost per RTO (forward + return shipping and any write-off).',
  '- Reprint = reprint rate × (supplier + shipping + packaging).',
  '- Landed = supplier + shipping + packaging + payment + RTO + reprint. Contribution = net revenue − landed.',
  '',
);

writeFileSync(REPORT, out.join('\n'));
// eslint-disable-next-line no-console
console.log(
  `${complete.length} complete, ${incomplete.length} incomplete row(s) → ${REPORT}`,
);
