// Contribution per unit, from verified inputs only.
//   npm run costs:check
//
// Reads ops/landed-cost.csv (fill it only from the supplier's own page,
// dashboard, invoice or written reply; gateway and GST from their own rate
// card / your CA) and the retail prices in app/data/catalogue/pricing.ts.
// A row with any blank input is reported as incomplete and gets NO figure:
// nothing is estimated or defaulted. A value confirmed to be zero (e.g. "no
// RTO charge") is entered as 0. Writes catalogue/landed-cost-report.md.
import {readFileSync, writeFileSync} from 'node:fs';
import {
  PRICE_OVERRIDES_INR,
  RETAIL_PRICE_INR,
} from '../app/data/catalogue/pricing.ts';
import type {ProductTypeHandle} from '../app/data/catalogue/types.ts';

const INPUT = 'ops/landed-cost.csv';
const REPORT = 'catalogue/landed-cost-report.md';
const TARGET_MARGINS = [0.5, 0.55, 0.6];

const NUMERIC = [
  'product_cost_inr',
  'print_cost_inr',
  'supplier_gst_pct',
  'shipping_inr',
  'shipping_gst_pct',
  'cod_fee_inr',
  'cod_fee_gst_pct',
  'rto_charge_inr',
  'gateway_fee_pct',
  'gateway_fixed_inr',
  'gateway_fee_gst_pct',
  'output_gst_pct',
] as const;
const BOOLEAN = ['supplier_prices_include_gst', 'itc_claimable'] as const;
const TEXT = ['source', 'quote_date'] as const;

type Row = Record<string, string>;
type Num = Record<(typeof NUMERIC)[number], number>;

function parseCsv(text: string): Row[] {
  const [header, ...lines] = text.trim().split(/\r?\n/);
  const keys = header.split(',');
  return lines
    .filter((line) => line.trim())
    .map((line) => {
      const cells = line.split(',');
      return Object.fromEntries(
        keys.map((k, i) => [k, (cells[i] ?? '').trim()]),
      );
    });
}

const yes = (v: string) => /^(y|yes|true|1)$/i.test(v);
const isBool = (v: string) => /^(y|yes|true|1|n|no|false|0)$/i.test(v);
const inr = (n: number) =>
  `₹${n.toLocaleString('en-IN', {maximumFractionDigits: 0})}`;
const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

/** A supplier charge as {ex GST, GST} from the quoted amount. */
function charge(amount: number, gstPct: number, quotedInclGst: boolean) {
  const rate = gstPct / 100;
  const ex = quotedInclGst ? amount / (1 + rate) : amount;
  return {ex, gst: ex * rate};
}

function contribution(n: Num, inclGst: boolean, itc: boolean) {
  const goods = charge(
    n.product_cost_inr + n.print_cost_inr,
    n.supplier_gst_pct,
    inclGst,
  );
  const ship = charge(n.shipping_inr, n.shipping_gst_pct, inclGst);
  const cod = charge(n.cod_fee_inr, n.cod_fee_gst_pct, inclGst);
  // With input tax credit the GST on a charge is recovered; without, it's a cost.
  const cost = (c: {ex: number; gst: number}) => (itc ? c.ex : c.ex + c.gst);
  const gatewayPct =
    (n.gateway_fee_pct / 100) * (itc ? 1 : 1 + n.gateway_fee_gst_pct / 100);
  const gatewayFixed =
    n.gateway_fixed_inr * (itc ? 1 : 1 + n.gateway_fee_gst_pct / 100);
  const fixed = cost(goods) + cost(ship);
  const outGst = n.output_gst_pct / 100;

  const at = (retail: number) => {
    const net = retail / (1 + outGst);
    const beforeFee = net - fixed;
    const gateway = retail * gatewayPct + gatewayFixed;
    const prepaid = beforeFee - gateway;
    const codOrder = beforeFee - cost(cod);
    return {net, beforeFee, gateway, prepaid, codOrder};
  };
  /** Retail price (incl. GST) giving margin `t` on net revenue. */
  const priceFor = (t: number, mode: 'prepaid' | 'cod') => {
    const k = (1 - t) / (1 + outGst);
    return mode === 'prepaid'
      ? (fixed + gatewayFixed) / (k - gatewayPct)
      : (fixed + cost(cod)) / k;
  };
  const inputGst = goods.gst + ship.gst;
  return {goods, ship, cod, fixed, at, priceFor, inputGst, outGst};
}

const rows = parseCsv(readFileSync(INPUT, 'utf8'));
const out: string[] = [
  '# Contribution per unit (before marketing)',
  '',
  `Generated by \`npm run costs:check\` from \`${INPUT}\` and \`app/data/catalogue/pricing.ts\`.`,
  'Rows with any blank or invalid input show no figures. Nothing is estimated.',
  '',
];
const complete: string[] = [];
const targets: string[] = [];
const gstRows: string[] = [];
const incomplete: string[] = [];

for (const row of rows) {
  const type = row.product_type as ProductTypeHandle;
  const retail = RETAIL_PRICE_INR[type];
  const label = `${type} / ${row.variant}`;
  const missing: string[] = [
    ...NUMERIC.filter((k) => row[k] === '' || Number.isNaN(Number(row[k]))),
    ...BOOLEAN.filter((k) => !isBool(row[k] ?? '')),
    ...TEXT.filter((k) => !row[k]),
  ];
  if (retail == null) missing.unshift('product_type (unknown)');
  if (missing.length) {
    incomplete.push(`| ${label} | ${missing.join(', ')} |`);
    continue;
  }

  const n = Object.fromEntries(NUMERIC.map((k) => [k, Number(row[k])])) as Num;
  const itc = yes(row.itc_claimable);
  const m = contribution(n, yes(row.supplier_prices_include_gst), itc);
  const r = m.at(retail);
  complete.push(
    `| ${label} | ${inr(retail)} | ${inr(r.net)} | ${inr(m.fixed)} | ${inr(r.beforeFee)} (${pct(r.beforeFee / r.net)}) | ${inr(r.gateway)} | ${inr(r.prepaid)} (${pct(r.prepaid / r.net)}) | ${inr(r.codOrder)} (${pct(r.codOrder / r.net)}) | ${inr(n.rto_charge_inr)} | ${row.source} (${row.quote_date}) |`,
  );
  targets.push(
    `| ${label} | ${TARGET_MARGINS.map((t) => `${inr(m.priceFor(t, 'prepaid'))} / ${inr(m.priceFor(t, 'cod'))}`).join(' | ')} |`,
  );
  const outputGst = retail - r.net;
  gstRows.push(
    `| ${label} | ${itc ? 'yes' : 'no'} | ${inr(outputGst)} | ${inr(m.inputGst)} | ${inr(itc ? outputGst - m.inputGst : outputGst)} |`,
  );
}

if (complete.length) {
  out.push(
    '## Contribution at current prices',
    '',
    'Supplier = product + print + supplier shipping (ex GST when input tax credit is claimable).',
    '',
    '| Product / variant | Retail (incl. GST) | Net revenue (ex GST) | Supplier | Before payment fee | Gateway fee | Prepaid | COD | Cost per RTO | Source |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...complete,
    '',
    'Margins are on net revenue. Contribution is before marketing, overheads and income tax. An RTO costs the amount shown each time it happens; no RTO rate is assumed.',
    '',
    '## Retail price (incl. GST) for a target margin: prepaid / COD',
    '',
    `| Product / variant | ${TARGET_MARGINS.map((t) => `${t * 100}%`).join(' | ')} |`,
    `| --- | ${TARGET_MARGINS.map(() => '---').join(' | ')} |`,
    ...targets,
    '',
    '## GST per unit at current prices',
    '',
    '| Product / variant | Input tax credit | Output GST collected | Input GST on supplier charges | Net GST payable |',
    '| --- | --- | --- | --- | --- |',
    ...gstRows,
    '',
  );
}
if (incomplete.length) {
  out.push(
    '## Incomplete rows (no figures shown)',
    '',
    '| Product / variant | Missing inputs |',
    '| --- | --- |',
    ...incomplete,
    '',
  );
}
if (Object.keys(PRICE_OVERRIDES_INR).length) {
  out.push(
    `Per-design price overrides exist (${Object.keys(PRICE_OVERRIDES_INR).join(', ')}); check them separately.`,
    '',
  );
}
out.push(
  '## Formula',
  '',
  '- Net revenue = retail ÷ (1 + output GST).',
  '- Supplier charges (product, print, shipping, COD fee) are taken ex GST when input tax credit is claimable, otherwise including GST.',
  '- Before payment fee = net revenue − product − print − supplier shipping.',
  '- Prepaid = before payment fee − gateway fee (retail × gateway % + fixed fee, plus GST on the fee unless claimable).',
  '- COD = before payment fee − supplier COD fee (no gateway fee on a COD order).',
  '- Target price solves: margin on net revenue = target, for prepaid and COD separately.',
  '',
);

writeFileSync(REPORT, out.join('\n'));
// eslint-disable-next-line no-console
console.log(
  `${complete.length} complete, ${incomplete.length} incomplete row(s) → ${REPORT}`,
);
