// Supplier template readiness + artwork fit (read-only).
//   npm run supplier:check
//
// Reports which supplier facts are still unconfirmed in
// ops/supplier-templates.ts and, where a print area is known, how each V1
// production master fits it (printed size and effective DPI), using the ink
// bounds measured by verify:artwork. Writes catalogue/supplier-templates.md.
// Never reads or writes the artwork itself.
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {LAUNCH_FAMILIES, PRODUCT_TYPES} from '../app/data/catalogue/index.ts';
import {SUPPLIERS} from '../ops/suppliers.ts';
import {
  MIN_EFFECTIVE_DPI,
  SUPPLIER_TEMPLATES,
  fitArtwork,
  missingTemplateFields,
} from '../ops/supplier-templates.ts';

const MANIFEST = 'catalogue/artwork-manifest.json';
const REPORT = 'catalogue/supplier-templates.md';

type ManifestEntry = {
  family: string;
  file: string;
  inkBounds: {x: [number, number]; y: [number, number]};
};
const manifest: ManifestEntry[] = existsSync(MANIFEST)
  ? (JSON.parse(readFileSync(MANIFEST, 'utf8')) as ManifestEntry[])
  : [];

const out = [
  '# Supplier templates (V1)',
  '',
  'Generated by `npm run supplier:check` from `ops/supplier-templates.ts`. Fill the template facts from each supplier’s spec sheet or designer tool, then re-run. Artwork is placed and scaled in the supplier’s designer; the PNG masters are never edited.',
  '',
];
let ready = 0;
let problems = 0;

for (const type of PRODUCT_TYPES) {
  const t = SUPPLIER_TEMPLATES[type.handle];
  const missing = missingTemplateFields(t);
  if (!missing.length) ready++;
  out.push(
    `## ${type.name} (\`${type.handle}\`)`,
    '',
    `- Supplier: ${SUPPLIERS[t.supplier].name}`,
    `- Blank: ${t.blankName ?? '—'} (${t.blankRef ?? 'ref —'}), colour: ${t.blankColour ?? '—'}`,
    `- Placement: ${t.placement}`,
    `- Print area: ${t.printArea ? `${t.printArea.widthIn} × ${t.printArea.heightIn} in` : '—'}`,
    `- Variant refs: ${Object.entries(t.variantRefs)
      .map(([k, v]) => `${k}=${v ?? '—'}`)
      .join(', ')}`,
    `- Source: ${t.source ?? '—'}`,
    `- Status: ${missing.length ? `**to confirm**: ${missing.join(', ')}` : 'confirmed'}`,
    '',
  );

  if (!t.printArea) continue;
  out.push(
    '| Master | Ink (px) | Printed size (in) | Effective DPI | OK |',
    '| --- | --- | --- | --- | --- |',
  );
  for (const family of LAUNCH_FAMILIES) {
    const entry = manifest.find((m) => m.file === family.artworkFile);
    if (!entry) {
      out.push(
        `| ${family.artworkFile} | not in manifest (run verify:artwork) | | | ✗ |`,
      );
      problems++;
      continue;
    }
    const ink = {
      widthPx: entry.inkBounds.x[1] - entry.inkBounds.x[0] + 1,
      heightPx: entry.inkBounds.y[1] - entry.inkBounds.y[0] + 1,
    };
    const fit = fitArtwork(ink, t.printArea);
    if (!fit.ok) problems++;
    out.push(
      `| ${family.artworkFile} | ${ink.widthPx}×${ink.heightPx} | ${fit.printedWidthIn} × ${fit.printedHeightIn} | ${fit.effectiveDpi} | ${fit.ok ? '✓' : `✗ below ${MIN_EFFECTIVE_DPI}`} |`,
    );
  }
  out.push('');
}

writeFileSync(REPORT, out.join('\n'));
// eslint-disable-next-line no-console
console.log(
  `${ready}/${PRODUCT_TYPES.length} supplier templates confirmed; ${problems} artwork fit problem(s) → ${REPORT}`,
);
if (problems) process.exitCode = 1;
